server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml  # 로그 수집 위치 저장 파일

clients:
  - url: http://3.34.223.104:3100/loki/api/v1/push  # Loki 서버 주소

scrape_configs:
  - job_name: spring-boot-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: "spring-boot-logs"
          application: spring-boot
          __path__: /home/ubuntu/test_dev/log/info/info.log
    pipeline_stages:
      - regex:
          expression: '^\[(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\] \[(?P<level>INFO|ERROR|WARN|DEBUG)\] (?P<class>[^-]+) - (?P<message>.*)$'
      - timestamp:
          source: time
          format: RFC3339

  - job_name: "error_logs"
    static_configs:
      - targets:
          - localhost
      - labels:
          job: "spring-boot-logs"
          level: "error"
          __path__: /home/ubuntu/test_dev/log/warn_error/error.log
    pipeline_stages:
      - regex:
          expression: '^\[(?P<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\] \[(?P<level>INFO|ERROR|WARN|DEBUG)\] (?P<class>[^-]+) - (?P<message>.*)$'
      - timestamp:
          source: time
          format: RFC3339