FROM openjdk:17-jdk-slim

WORKDIR /app

ARG BACKEND_DOMAIN
ARG BASIC_URL
ARG BUCKET
ARG DB_PASSWORD
ARG DB_URL
ARG DB_USERNAME
ARG FRONTEND_DOMAIN
ARG GOOGLE_ID
ARG GOOGLE_SECRET
ARG REDIRECT_URI
ARG S3_ACCESS_KEY
ARG S3_SECRET_KEY
ARG TEST_BACKEND_DOMAIN
ARG TEST_FRONTEND_DOMAIN

ENV BACKEND_DOMAIN=${BACKEND_DOMAIN} \
BASIC_URL=${BASIC_URL} \
BUCKET=${BUCKET} \
DB_PASSWORD=${DB_PASSWORD} \
DB_URL=${DB_URL} \
DB_USERNAME=${DB_USERNAME} \
FRONTEND_DOMAIN=${FRONTEND_DOMAIN} \
GOOGLE_ID=${GOOGLE_ID} \
GOOGLE_SECRET=${GOOGLE_SECRET} \
REDIRECT_URI=${REDIRECT_URI} \
S3_ACCESS_KEY=${S3_ACCESS_KEY} \
S3_SECRET_KEY=${S3_SECRET_KEY} \
TEST_BACKEND_DOMAIN=${TEST_BACKEND_DOMAIN} \
TEST_FRONTEND_DOMAIN=${TEST_FRONTEND_DOMAIN}

ARG JAR_FILE=build/libs/dev-0.0.1-SNAPSHOT.jar

COPY ${JAR_FILE} dev-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "dev-0.0.1-SNAPSHOT.jar"]