services:
#  redis:
#    image: redis:latest
#    container_name: redis-server
#    ports:
#      - "6379:6379"

  postgres:
    image: postgres:17
    container_name: postgres-container
    environment:
      POSTGRES_USER: hwang
      POSTGRES_PASSWORD: hwang1234!@
      POSTGRES_DB: mildo
    ports:
      - "5432:5432"
    volumes:
      - C:\projects\storage\mildo\postgresql:/var/lib/postgresql/data