cloud:
  aws:
    credentials:
      access-key: "${TEST_S3_ACCESS_KEY}"
      secret-key: "${TEST_S3_SECRET_KEY}"
    region:
      static: ap-northeast-2
    s3:
      bucket: "${TEST_BUCKET}"
    stack:
      auto: false

spring:
  datasource:
    url: "${TEST_DB_URL}"
    username: "${TEST_DB_USERNAME}"
    password: "${TEST_DB_PASSWORD}"

server:
  port: 8008

domain:
  front: "${TEST_FRONTEND_DOMAIN}"
  back: "${TEST_BACKEND_DOMAIN}"